/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Desktop;
import java.awt.Dialog;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;


/**
 *
 * @author Nacho
 */
public class VInformes extends javax.swing.JPanel {

    private final String texto_estado_vista = "vista";
    private final String texto_estado_editar = "editar";
    private final String texto_estado_nuevo = "nuevo";
    private final String texto_campo_vacio = "";
    private String estado = texto_estado_vista;

    private final String texto_boton_01 = "Informe 1";
    private final String texto_boton_02 = "Informe 2";
    private final String texto_boton_03 = "Informe 3";
    private final String texto_boton_04 = "Informe 4";

    //parte de botones
    private final String texto_Editar = "Editar";
    private final String texto_Guardar = "Guardar";
    private final String texto_Cancelar = "Cancelar";
    private final String texto_Borrar = "Borrar";

    private final String MSG_Usuario_modificado_correctamente
            = "El usuario ha sido modificado correctamente";

    Connection conexion = null;
    private Map<String, Object> parametros;
//    private String reportSource = "./reportes/templates/informe";
//    private String reportDest = "./reportes/";

    private String reportSource = "c:\\proyecto\\reportes\\templates\\informe.jrxml";
    private String reportDest = "c:\\proyecto\\reportes\\";

    private ResultSet rs;

    /**
     * Creates new form vUsuarios
     */
    public VInformes() {
        GroupLayout layout = new GroupLayout(this);
        setLayout(layout);
        setBounds(0, 0, 1185, 677);
        initComponents();

        boton_01.setText(texto_boton_01);
        boton_02.setText(texto_boton_02);
        boton_03.setText(texto_boton_03);
        boton_04.setText(texto_boton_04);

        bloquearCampos();

    }

    public JPanel getVContactos() {
        updateUI();
        return this;
    }

    /**
     * Bloqueamos los campos para que no sean modificables
     */
    public void bloquearCampos() {

    }

    /**
     * Desbloqueamos los campos para que sean modificables
     */
    public void desbloquearCampos() {

    }

    /**
     * Limpia todos los campos
     */
    public void limpiarCampos() {

    }

    public void setDatos(ResultSet rs) {
        this.rs = rs;
        try {
            rs.next();
        } catch (SQLException ex) {
            Logger.getLogger(VSesion.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje, "Información del sistema",
                JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boton_01 = new javax.swing.JButton();
        boton_02 = new javax.swing.JButton();
        boton_03 = new javax.swing.JButton();
        boton_04 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(900, 710));
        setPreferredSize(new java.awt.Dimension(900, 710));

        boton_01.setText("boton_01");
        boton_01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_01ActionPerformed(evt);
            }
        });

        boton_02.setText("boton_02");
        boton_02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_02ActionPerformed(evt);
            }
        });

        boton_03.setText("boton_04");
        boton_03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_03ActionPerformed(evt);
            }
        });

        boton_04.setText("boton_03");
        boton_04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_04ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(375, 375, 375)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boton_03)
                    .addComponent(boton_04)
                    .addComponent(boton_02)
                    .addComponent(boton_01))
                .addContainerGap(442, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(boton_01)
                .addGap(18, 18, 18)
                .addComponent(boton_02)
                .addGap(18, 18, 18)
                .addComponent(boton_04)
                .addGap(18, 18, 18)
                .addComponent(boton_03)
                .addContainerGap(549, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void boton_01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_01ActionPerformed

        conexion = VentanaPrincipal.getConexion();
        
        //Cargamos los parametros del informe en una tabla Hash
        parametros = new HashMap<String, Object>();
//        parametros.put("Titulo", "Resumen de sesiones");
//        parametros.put("Autor", "Nacho");
//        parametros.put("Fecha", new Date().toString());

        try {
            //si lo queremos hacer con la plantilla, con el .jasper
            // JasperReport jasperReport= JasperCompileManager.compileReport(reportSource);
            //JasperPrint print = JasperFillManager.fillReport(jasperReport, parametros, conexion);

            //Generamos el informe en memoria
            //JasperPrint print = JasperFillManager.fillReport(reportSource, parametros, conexion);
            //parar verlo
            //JasperViewer.viewReport(print);

            // Exporta el informe a PDF  
            //JasperExportManager.exportReportToPdfFile(print, "informe.pdf");

            //Abre el archivo PDF generado
            File path = new File("c:\\proyecto\\reportes\\results\\informe.pdf");
            Desktop.getDesktop().open(path);

            // Exportar a Html
            //JasperExportManager.exportReportToHtmlFile(print, reportDest + "informe.html");
            // Exportar a XML
            //JasperExportManager.exportReportToXmlFile(print, reportDest + "informe.xml", true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString(), "Error", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_boton_01ActionPerformed

    private void boton_02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_02ActionPerformed


    }//GEN-LAST:event_boton_02ActionPerformed

    private void boton_04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_04ActionPerformed

    private void boton_03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_03ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_03ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_01;
    private javax.swing.JButton boton_02;
    private javax.swing.JButton boton_03;
    private javax.swing.JButton boton_04;
    // End of variables declaration//GEN-END:variables
}
